### ISSUE TITLE
VWSフォーラムがおかしいです。

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/lightning-bbpress-extension#1]
VWSフォーラムがおかしいです。
（ここで書くべき事項かは不明ですがbbPressに関連する事項と思われるので）
①フォーラムに返信ができないようです（私だけ？）
②〇〇時間前等の表記が英語表記になっています。

**Comment by kurudrive** [comment]
ありがとうございます。確認します。

**Comment by kurudrive** [comment]
@naogify 確認よろしくお願いいたします ＞ｗ＜

**Comment by naogify** [comment]
@rick-addison 
ご報告ありがとうございます。確認します!

**Comment by naogify** [comment]
@rick-addison 修正しました。また不具合などあればご報告頂けるとありがたいです!
